openapi: 3.0.3
info:
  title: Hello World!
  description: Hello World!
  version: 1.0.0
servers:
  - url: 'https://hello-world.omegapoint.se'
paths:
  /hello-world:
    get:
      summary: Returns hello world
      responses:
        200:
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'

      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: HelloWorldHandler

components:
  schemas:
    HelloWorldResponse:
      type: object
      properties:
        message:
          type: string